using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OlimpBack.Data;

#nullable disable

namespace OlimpBack.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429190000_RbacCamelCaseAccessModel")]
    public partial class RbacCamelCaseAccessModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF to_regclass('roles') IS NOT NULL AND to_regclass('"Roles"') IS NULL THEN
        ALTER TABLE roles RENAME TO "Roles";
    END IF;

    IF to_regclass('permissions') IS NOT NULL AND to_regclass('"Permissions"') IS NULL THEN
        ALTER TABLE permissions RENAME TO "Permissions";
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "Roles" (
    id_role integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    parent_role_id integer NULL,
    permissions_mask bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "Permissions" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL,
    bit_index integer NOT NULL
);

ALTER TABLE "Roles"
    ADD COLUMN IF NOT EXISTS parent_role_id integer NULL,
    ADD COLUMN IF NOT EXISTS permissions_mask bigint NOT NULL DEFAULT 0;

ALTER TABLE "Permissions"
    ADD COLUMN IF NOT EXISTS bit_index integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS "Permissions_code_key" ON "Permissions" (code);
CREATE UNIQUE INDEX IF NOT EXISTS "Permissions_bitIndex_key" ON "Permissions" (bit_index);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'Roles_parentRole_fk'
    ) THEN
        ALTER TABLE "Roles"
            ADD CONSTRAINT "Roles_parentRole_fk"
            FOREIGN KEY (parent_role_id) REFERENCES "Roles"(id_role) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "RolePermissions" (
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT "RolePermissions_pkey" PRIMARY KEY (role_id, permission_id),
    CONSTRAINT "RolePermissions_Roles_fk" FOREIGN KEY (role_id) REFERENCES "Roles"(id_role) ON DELETE CASCADE,
    CONSTRAINT "RolePermissions_Permissions_fk" FOREIGN KEY (permission_id) REFERENCES "Permissions"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT "UserRoles_pkey" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "UserRoles_Users_fk" FOREIGN KEY (user_id) REFERENCES "Users"("idUser") ON DELETE CASCADE,
    CONSTRAINT "UserRoles_Roles_fk" FOREIGN KEY (role_id) REFERENCES "Roles"(id_role) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserRoles_userId" ON "UserRoles" (user_id);
CREATE INDEX IF NOT EXISTS "IX_UserRoles_roleId" ON "UserRoles" (role_id);

INSERT INTO "Permissions" (id, code, bit_index)
VALUES
    (1, 'users.create', 0),
    (2, 'users.read', 1),
    (3, 'users.update', 2),
    (4, 'users.delete', 3),
    (5, 'roles.create', 4),
    (6, 'roles.read', 5),
    (7, 'roles.update', 6),
    (8, 'roles.delete', 7),
    (9, 'permissions.create', 8),
    (10, 'permissions.read', 9),
    (11, 'permissions.update', 10),
    (12, 'permissions.delete', 11),
    (13, 'rolePermissions.create', 12),
    (14, 'rolePermissions.read', 13),
    (15, 'rolePermissions.update', 14),
    (16, 'rolePermissions.delete', 15),
    (17, 'students.create', 16),
    (18, 'students.read', 17),
    (19, 'students.update', 18),
    (20, 'students.delete', 19),
    (21, 'faculties.create', 20),
    (22, 'faculties.read', 21),
    (23, 'faculties.update', 22),
    (24, 'faculties.delete', 23),
    (25, 'departments.create', 24),
    (26, 'departments.read', 25),
    (27, 'departments.update', 26),
    (28, 'departments.delete', 27),
    (29, 'groups.create', 28),
    (30, 'groups.read', 29),
    (31, 'groups.update', 30),
    (32, 'groups.delete', 31),
    (33, 'educationalPrograms.create', 32),
    (34, 'educationalPrograms.read', 33),
    (35, 'educationalPrograms.update', 34),
    (36, 'educationalPrograms.delete', 35),
    (37, 'educationalDegrees.create', 36),
    (38, 'educationalDegrees.read', 37),
    (39, 'educationalDegrees.update', 38),
    (40, 'educationalDegrees.delete', 39),
    (41, 'mainDisciplines.create', 40),
    (42, 'mainDisciplines.read', 41),
    (43, 'mainDisciplines.update', 42),
    (44, 'mainDisciplines.delete', 43),
    (45, 'discipline.create', 44),
    (46, 'discipline.read', 45),
    (47, 'discipline.update', 46),
    (48, 'discipline.delete', 47),
    (49, 'discipline.teachersPermission', 48),
    (50, 'disciplineChoicePeriods.create', 49),
    (51, 'disciplineChoicePeriods.read', 50),
    (52, 'disciplineChoicePeriods.update', 51),
    (53, 'disciplineChoicePeriods.delete', 52),
    (54, 'notifications.create', 53),
    (55, 'notifications.read', 54),
    (56, 'notifications.update', 55),
    (57, 'notifications.delete', 56),
    (58, 'parameters.create', 57),
    (59, 'parameters.read', 58),
    (60, 'parameters.update', 59),
    (61, 'parameters.delete', 60)
ON CONFLICT (code) DO UPDATE
SET bit_index = EXCLUDED.bit_index;

SELECT setval(
    pg_get_serial_sequence('"Permissions"', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM "Permissions"), 1),
    true
)
WHERE pg_get_serial_sequence('"Permissions"', 'id') IS NOT NULL;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS "UserRoles";
DROP TABLE IF EXISTS "RolePermissions";
ALTER TABLE "Roles" DROP CONSTRAINT IF EXISTS "Roles_parentRole_fk";
DROP INDEX IF EXISTS "Permissions_bitIndex_key";
""");
        }
    }
}
