// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OlimpBack.Infrastructure.Database;

#nullable disable

namespace OlimpBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422175549_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OlimpBack.Models.Achievement", b =>
                {
                    b.Property<int>("IdAchievement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idAchievement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAchievement"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.HasKey("IdAchievement");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.AddDetail", b =>
                {
                    b.Property<int>("IdAddDetails")
                        .HasColumnType("integer")
                        .HasColumnName("idAddDetails");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineTopics")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Language")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Provision")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Recomend")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("ResultEducation")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Teachers")
                        .HasColumnType("json");

                    b.Property<string>("TypeOfControll")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypesOfTraining")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UsingIrl")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("UsingIRL");

                    b.Property<string>("WhyInterestingDetermination")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.HasKey("IdAddDetails");

                    b.HasIndex(new[] { "DepartmentId" }, "AddDetails_Departments");

                    b.HasIndex(new[] { "IdAddDetails" }, "idAddDeteils_UNIQUE")
                        .IsUnique();

                    b.ToTable("AddDetails");
                });

            modelBuilder.Entity("OlimpBack.Models.AddDiscipline", b =>
                {
                    b.Property<int>("IdAddDisciplines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idAddDisciplines");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddDisciplines"));

                    b.Property<string>("CodeAddDisciplines")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("codeAddDisciplines");

                    b.Property<int?>("DegreeLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("IdCatalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCatalog")
                        .HasDefaultValueSql("1");

                    b.Property<short?>("IsEven")
                        .HasColumnType("smallint");

                    b.Property<short>("IsFaculty")
                        .HasColumnType("smallint");

                    b.Property<short>("IsForseChange")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaxCountPeople")
                        .HasColumnType("integer")
                        .HasColumnName("maxCountPeople");

                    b.Property<int?>("MaxCourse")
                        .HasColumnType("integer")
                        .HasColumnName("maxCourse");

                    b.Property<int?>("MinCountPeople")
                        .HasColumnType("integer")
                        .HasColumnName("minCountPeople");

                    b.Property<int?>("MinCourse")
                        .HasColumnType("integer")
                        .HasColumnName("minCourse");

                    b.Property<string>("NameAddDisciplines")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameAddDisciplines");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("IdAddDisciplines");

                    b.HasIndex(new[] { "FacultyId" }, "AddDisciplines_ Faculties_idx");

                    b.HasIndex(new[] { "IdCatalog" }, "AddDisciplines_CatalogYears_FK");

                    b.HasIndex(new[] { "DegreeLevelId" }, "AddDisciplines_EducationalDegree_idx");

                    b.HasIndex(new[] { "TypeId" }, "AddDisciplines_Type_idx");

                    b.HasIndex(new[] { "IdAddDisciplines" }, "idAddDisciplines_UNIQUE")
                        .IsUnique();

                    b.ToTable("AddDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.AdminLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime>("ChangeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasComment("idUsers who performed action");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Primary key of affected row");

                    b.Property<string>("NewData")
                        .HasColumnType("json");

                    b.Property<string>("OldData")
                        .HasColumnType("json");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("LogId", "ChangeTime");

                    b.HasIndex(new[] { "AdminId" }, "idx_AdminLogs_AdminId");

                    b.HasIndex(new[] { "ChangeTime" }, "idx_AdminLogs_Time");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("OlimpBack.Models.AdminsPersonal", b =>
                {
                    b.Property<int>("IdAdmins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idAdmins");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdmins"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("NameAdmin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameAdmin");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdAdmins");

                    b.HasIndex(new[] { "DepartmentId" }, "AdminsPersonal_Department_idx");

                    b.HasIndex(new[] { "FacultyId" }, "AdminsPersonal_Faculties_idx");

                    b.HasIndex(new[] { "UserId" }, "AdminsPersonal_Users_idx");

                    b.ToTable("AdminsPersonal", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.BindAddDiscipline", b =>
                {
                    b.Property<int>("IdBindAddDisciplines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindAddDisciplines");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindAddDisciplines"));

                    b.Property<int>("AddDisciplinesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<short>("InProcess")
                        .HasColumnType("smallint")
                        .HasColumnName("inProcess");

                    b.Property<int>("Loans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("5");

                    b.Property<int>("Semestr")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("IdBindAddDisciplines");

                    b.HasIndex(new[] { "AddDisciplinesId" }, "Bind_AddCourse_idx");

                    b.HasIndex(new[] { "StudentId" }, "Bind_Student_idx");

                    b.ToTable("BindAddDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.BindEvent", b =>
                {
                    b.Property<int>("IdBindEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindEvent");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindEvent"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("EventID");

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("IdBindEvent");

                    b.HasIndex(new[] { "EventId" }, "EventID");

                    b.HasIndex(new[] { "StudentId" }, "StudentId");

                    b.ToTable("BindEvents");
                });

            modelBuilder.Entity("OlimpBack.Models.BindExtraActivity", b =>
                {
                    b.Property<int>("IdBindExtraActivity")
                        .HasColumnType("integer")
                        .HasColumnName("idBindExtraActivity");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("RefulationId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("IdBindExtraActivity");

                    b.HasIndex(new[] { "RefulationId" }, "BindExtraActivity_Regulation_idx");

                    b.HasIndex(new[] { "StudentId" }, "BindExtraActivity_Student");

                    b.ToTable("BindExtraActivity", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.BindLoansMain", b =>
                {
                    b.Property<int>("IdBindLoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindLoan");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindLoan"));

                    b.Property<int>("AddDisciplinesId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("integer");

                    b.HasKey("IdBindLoan");

                    b.HasIndex(new[] { "AddDisciplinesId" }, "BindLoansMain_AddDisciplines_idx");

                    b.HasIndex(new[] { "EducationalProgramId" }, "BindLoansMain_EducationalProgram_idx");

                    b.ToTable("BindLoansMain", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.BindMainDiscipline", b =>
                {
                    b.Property<int>("IdBindMainDisciplines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindMainDisciplines");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindMainDisciplines"));

                    b.Property<string>("CodeMainDisciplines")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("codeMainDisciplines");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("integer");

                    b.Property<string>("FormControll")
                        .HasColumnType("text");

                    b.Property<int?>("Hours")
                        .HasColumnType("integer")
                        .HasComment("Години");

                    b.Property<int>("Loans")
                        .HasColumnType("integer");

                    b.Property<string>("NameBindMainDisciplines")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nameBindMainDisciplines");

                    b.Property<int>("Semestr")
                        .HasColumnType("integer");

                    b.Property<string>("Teachers")
                        .HasColumnType("json");

                    b.HasKey("IdBindMainDisciplines");

                    b.HasIndex(new[] { "EducationalProgramId" }, "BindMainDisciplines_EducationalProgram_idx");

                    b.ToTable("BindMainDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.BindRolePermission", b =>
                {
                    b.Property<int>("IdBindRolePermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindRolePermission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindRolePermission"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("IdBindRolePermission");

                    b.HasIndex(new[] { "PermissionId" }, "BindRolePermission_Permission_idx");

                    b.HasIndex(new[] { "RoleId" }, "BindRolePermission_Role_idx");

                    b.ToTable("BindRolePermission", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.BindStudentsFavouriteDiscipline", b =>
                {
                    b.Property<int>("IdBindStudentsFavouriteDisciplines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBindStudentsFavouriteDisciplines");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBindStudentsFavouriteDisciplines"));

                    b.Property<int?>("IdAddDiscipline")
                        .HasColumnType("integer")
                        .HasColumnName("idAddDiscipline");

                    b.Property<int?>("IdStudent")
                        .HasColumnType("integer")
                        .HasColumnName("idStudent");

                    b.HasKey("IdBindStudentsFavouriteDisciplines");

                    b.HasIndex(new[] { "IdAddDiscipline" }, "BindStudentsFavouriteDisciplines_AddDisciplines_FK");

                    b.HasIndex(new[] { "IdStudent" }, "BindStudentsFavouriteDisciplines_Student_FK");

                    b.ToTable("BindStudentsFavouriteDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.Branch", b =>
                {
                    b.Property<int>("IdBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idBranch");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBranch"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code")
                        .HasComment("Код галузі (наприклад, 12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Назва галузі (наприклад, Інформаційні технології)");

                    b.HasKey("IdBranch");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.CatalogYear", b =>
                {
                    b.Property<int>("IdCatalogYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCatalogYear");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCatalogYear"));

                    b.Property<short>("IsFormed")
                        .HasColumnType("smallint")
                        .HasColumnName("isFormed");

                    b.Property<string>("NameCatalog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCatalogYear");

                    b.ToTable("CatalogYears", t =>
                        {
                            t.HasComment("Катлог за навчальним роками.");
                        });
                });

            modelBuilder.Entity("OlimpBack.Models.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDepartment");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("1");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameDepartment");

                    b.HasKey("IdDepartment");

                    b.HasIndex(new[] { "AdminId" }, "Department_Admin_idx");

                    b.HasIndex(new[] { "FacultyId" }, "Department_Faculties_idx");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.DisciplineChoicePeriod", b =>
                {
                    b.Property<int>("IdDisciplineChoicePeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDisciplineChoicePeriod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDisciplineChoicePeriod"));

                    b.Property<int>("DegreeLevelId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<short>("IsClose")
                        .HasColumnType("smallint");

                    b.Property<short>("PeriodCourse")
                        .HasColumnType("smallint");

                    b.Property<short>("PeriodType")
                        .HasColumnType("smallint")
                        .HasComment("Для всіх = 0, Перевибір = 1");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IdDisciplineChoicePeriod");

                    b.HasIndex(new[] { "DegreeLevelId" }, "fk_dcp_degreeLevel_idx");

                    b.HasIndex(new[] { "DepartmentId" }, "fk_dcp_department");

                    b.HasIndex(new[] { "FacultyId" }, "fk_dcp_faculty");

                    b.ToTable("DisciplineChoicePeriod", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.EducationStatus", b =>
                {
                    b.Property<int>("IdEducationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("idEducationStatus");

                    b.Property<string>("NameEducationStatus")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nameEducationStatus");

                    b.HasKey("IdEducationStatus");

                    b.HasIndex(new[] { "IdEducationStatus" }, "idEducationStatus_UNIQUE")
                        .IsUnique();

                    b.ToTable("EducationStatus", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.EducationalDegree", b =>
                {
                    b.Property<int>("IdEducationalDegree")
                        .HasColumnType("integer")
                        .HasColumnName("idEducationalDegree");

                    b.Property<string>("NameEducationalDegreec")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nameEducationalDegreec");

                    b.HasKey("IdEducationalDegree");

                    b.ToTable("EducationalDegree", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.EducationalProgram", b =>
                {
                    b.Property<int>("IdEducationalProgram")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idEducationalProgram");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEducationalProgram"));

                    b.Property<short>("Accreditation")
                        .HasColumnType("smallint")
                        .HasColumnName("accreditation");

                    b.Property<string>("AccreditationType")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("accreditationType");

                    b.Property<int?>("CountAddSemestr3")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr3");

                    b.Property<int?>("CountAddSemestr4")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr4");

                    b.Property<int?>("CountAddSemestr5")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr5");

                    b.Property<int?>("CountAddSemestr6")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr6");

                    b.Property<int?>("CountAddSemestr7")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr7");

                    b.Property<int?>("CountAddSemestr8")
                        .HasColumnType("integer")
                        .HasColumnName("countAddSemestr8");

                    b.Property<int>("DegreeId")
                        .HasColumnType("integer")
                        .HasColumnName("degreeId");

                    b.Property<string>("NameEducationalProgram")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameEducationalProgram");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("speciality");

                    b.Property<string>("SpecialityCode")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("specialityCode");

                    b.Property<int>("StudentsAmount")
                        .HasColumnType("integer")
                        .HasColumnName("studentsAmount");

                    b.HasKey("IdEducationalProgram");

                    b.HasIndex(new[] { "DegreeId" }, "EducationalProgram_EducationalDegree_idx");

                    b.ToTable("EducationalProgram", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idEvent");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvent"));

                    b.Property<int?>("AmountPeople")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LinkToRegistration")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NameEvent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nameEvent");

                    b.Property<int>("RegulationId")
                        .HasColumnType("integer");

                    b.HasKey("IdEvent");

                    b.HasIndex(new[] { "RegulationId" }, "Event_Regultion_idx");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OlimpBack.Models.Faculty", b =>
                {
                    b.Property<int>("IdFaculty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idFaculty");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFaculty"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("NameFaculty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameFaculty");

                    b.HasKey("IdFaculty");

                    b.HasIndex(new[] { "AdminId" }, "Faculties_Admin_idx");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("OlimpBack.Models.Group", b =>
                {
                    b.Property<int>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idGroup");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGroup"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdmissionYear")
                        .HasColumnType("integer")
                        .HasComment("Рік вступу");

                    b.Property<int?>("Course")
                        .HasColumnType("integer");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("IdEducationalProgram")
                        .HasColumnType("integer")
                        .HasColumnName("idEducationalProgram")
                        .HasComment("Освітня програма");

                    b.Property<int?>("IdSpeciality")
                        .HasColumnType("integer")
                        .HasColumnName("idSpeciality")
                        .HasComment("Спеціальність");

                    b.Property<int?>("IdSpecialization")
                        .HasColumnType("integer")
                        .HasColumnName("idSpecialization")
                        .HasComment("Спеціалізація");

                    b.Property<int?>("IdStudyForm")
                        .HasColumnType("integer")
                        .HasColumnName("idStudyForm")
                        .HasComment("Форма навчання");

                    b.Property<bool>("IsAccelerated")
                        .HasColumnType("boolean")
                        .HasComment("Чи прискорений (0 - ні, 1 - так)");

                    b.Property<int?>("NumberOfStudents")
                        .HasColumnType("integer");

                    b.HasKey("IdGroup");

                    b.HasIndex(new[] { "IdEducationalProgram" }, "FK_Group_EducationalProgram");

                    b.HasIndex(new[] { "IdSpeciality" }, "FK_Group_Speciality");

                    b.HasIndex(new[] { "IdSpecialization" }, "FK_Group_Specialization");

                    b.HasIndex(new[] { "IdStudyForm" }, "FK_Group_StudyForm");

                    b.HasIndex(new[] { "AdminId" }, "Group_Admin_idx");

                    b.HasIndex(new[] { "DepartmentId" }, "Group_Department");

                    b.HasIndex(new[] { "DegreeId" }, "Group_Department_idx");

                    b.HasIndex(new[] { "FacultyId" }, "Group_Faculties");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.MainGrade", b =>
                {
                    b.Property<int>("IdMainGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idMainGrade");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMainGrade"));

                    b.Property<int>("MainDisciplinesId")
                        .HasColumnType("integer");

                    b.Property<int?>("MainGrade1")
                        .HasColumnType("integer")
                        .HasColumnName("MainGrade");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("IdMainGrade");

                    b.HasIndex(new[] { "StudentId" }, "FK_MainGrade_Student");

                    b.HasIndex(new[] { "MainDisciplinesId" }, "MainGrade_MainDisciplines_idx");

                    b.ToTable("MainGrade", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Member", b =>
                {
                    b.Property<int>("IdMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idMember");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMember"));

                    b.Property<int>("RoleInSgid")
                        .HasColumnType("integer")
                        .HasColumnName("RoleInSGID");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubDivisionId")
                        .HasColumnType("integer");

                    b.HasKey("IdMember");

                    b.HasIndex(new[] { "RoleInSgid" }, "RoleInSGID");

                    b.HasIndex(new[] { "StudentId" }, "StudentId")
                        .HasDatabaseName("StudentId1");

                    b.HasIndex(new[] { "SubDivisionId" }, "SubDivisionId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("OlimpBack.Models.Normative", b =>
                {
                    b.Property<int>("IdNormative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idNormative");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNormative"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("DegreeLevelId")
                        .HasColumnType("integer");

                    b.Property<short>("IsFaculty")
                        .HasColumnType("smallint");

                    b.HasKey("IdNormative");

                    b.HasIndex(new[] { "DegreeLevelId" }, "Normative_Degree_idx");

                    b.ToTable("Normative", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idNotification");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdNotification");

                    b.HasIndex(new[] { "TemplateId" }, "Notification_NotificationTemplate_idx");

                    b.HasIndex(new[] { "UserId" }, "Notification_Users_idx");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OlimpBack.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("IdNotificationTemplates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idNotificationTemplates");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificationTemplates"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdNotificationTemplates");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity("OlimpBack.Models.Permission", b =>
                {
                    b.Property<int>("IdPermissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPermissions");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermissions"));

                    b.Property<int>("BitIndex")
                        .HasColumnType("integer")
                        .HasColumnName("bit_index");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TypePermission")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("IdPermissions");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("OlimpBack.Models.RegulationOnAddPoint", b =>
                {
                    b.Property<int>("IdRegulationOnAddPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRegulationOnAddPoints");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegulationOnAddPoints"));

                    b.Property<int>("AmountMax")
                        .HasColumnType("integer")
                        .HasColumnName("amountMax");

                    b.Property<int?>("AmountMin")
                        .HasColumnType("integer")
                        .HasColumnName("amountMin");

                    b.Property<string>("CodeRegulationOnAddPoints")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("codeRegulationOnAddPoints");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeOfActivitys")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("typeOfActivitys");

                    b.HasKey("IdRegulationOnAddPoints");

                    b.ToTable("RegulationOnAddPoints");
                });

            modelBuilder.Entity("OlimpBack.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRole");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<short?>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("0");

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nameRole");

                    b.Property<int?>("ParentRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_role_id");

                    b.Property<long>("PermissionsMask")
                        .HasColumnType("bigint")
                        .HasColumnName("permissions_mask");

                    b.HasKey("IdRole");

                    b.HasIndex("ParentRoleId");

                    b.HasIndex(new[] { "IdRole" }, "idRole_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "NameRole" }, "nameRole_UNIQUE")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.RolesInSg", b =>
                {
                    b.Property<int>("IdRoleSg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRoleSG");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRoleSg"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameRole");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("IdRoleSg");

                    b.ToTable("RolesInSG", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Speciality", b =>
                {
                    b.Property<int>("IdSpeciality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idSpeciality");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpeciality"));

                    b.Property<bool?>("Accreditation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("accreditation")
                        .HasDefaultValueSql("0")
                        .HasComment("Акредитація (0 або 1)");

                    b.Property<string>("AccreditationType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("accreditationType")
                        .HasComment("Тип акредитації (текст зі скріншоту)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code")
                        .HasComment("Код спеціальності (наприклад, 121)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Опис спеціальності");

                    b.Property<int?>("IdBranch")
                        .HasColumnType("integer")
                        .HasColumnName("idBranch")
                        .HasComment("Зовнішній ключ на Галузь");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("integer")
                        .HasColumnName("idDepartment")
                        .HasComment("Зовнішній ключ на Кафедру");

                    b.Property<int?>("IdFaculty")
                        .HasColumnType("integer")
                        .HasColumnName("idFaculty")
                        .HasComment("Зовнішній ключ на Факультет");

                    b.Property<int?>("LicensedVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("licensedVolume")
                        .HasDefaultValueSql("0")
                        .HasComment("Ліцензійний обсяг (studentsAmount)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Назва спеціальності");

                    b.HasKey("IdSpeciality");

                    b.HasIndex(new[] { "IdBranch" }, "FK_Speciality_Branch");

                    b.HasIndex(new[] { "IdDepartment" }, "FK_Speciality_Department");

                    b.HasIndex(new[] { "IdFaculty" }, "FK_Speciality_Faculty");

                    b.ToTable("Speciality", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Specialization", b =>
                {
                    b.Property<int>("IdSpecialization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idSpecialization");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecialization"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasComment("Код спеціалізації (наприклад, 014.01)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Опис спеціалізації");

                    b.Property<int>("IdSpeciality")
                        .HasColumnType("integer")
                        .HasColumnName("idSpeciality")
                        .HasComment("Зовнішній ключ на Спеціальність");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Назва спеціалізації");

                    b.HasKey("IdSpecialization");

                    b.HasIndex(new[] { "IdSpeciality" }, "FK_Specialization_Speciality");

                    b.ToTable("Specialization", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idStudent");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("Achievement")
                        .HasColumnType("json");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EducationEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EducationStart")
                        .HasColumnType("date");

                    b.Property<int>("EducationStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationalDegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInSg")
                        .HasColumnType("boolean")
                        .HasColumnName("IsInSG");

                    b.Property<short>("IsShort")
                        .HasColumnType("smallint");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameStudent");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int>("StudyFormId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdStudent");

                    b.HasIndex(new[] { "DepartmentId" }, "Students_Department_idx");

                    b.HasIndex(new[] { "EducationStatusId" }, "Students_EducationStatus_idx");

                    b.HasIndex(new[] { "EducationalDegreeId" }, "Students_EducationalDegree_idx");

                    b.HasIndex(new[] { "EducationalProgramId" }, "Students_EducationalProgram_idx");

                    b.HasIndex(new[] { "FacultyId" }, "Students_Faculties_idx");

                    b.HasIndex(new[] { "GroupId" }, "Students_Group_idx");

                    b.HasIndex(new[] { "StudyFormId" }, "Students_StudyForm_idx");

                    b.HasIndex(new[] { "UserId" }, "Students_Users_idx");

                    b.HasIndex(new[] { "IdStudent" }, "idStudent_UNIQUE")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.StudyForm", b =>
                {
                    b.Property<int>("IdStudyForm")
                        .HasColumnType("integer")
                        .HasColumnName("idStudyForm");

                    b.Property<string>("NameStudyForm")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nameStudyForm");

                    b.HasKey("IdStudyForm");

                    b.ToTable("StudyForm", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.SubDivisionsSg", b =>
                {
                    b.Property<int>("IdSubDivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idSubDivision");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSubDivision"));

                    b.Property<string>("NameDivision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdSubDivision");

                    b.ToTable("SubDivisionsSG", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.TypeOfDiscipline", b =>
                {
                    b.Property<int>("IdTypeOfDiscipline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTypeOfDiscipline");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeOfDiscipline"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("IdTypeOfDiscipline");

                    b.ToTable("TypeOfDiscipline", (string)null);
                });

            modelBuilder.Entity("OlimpBack.Models.User", b =>
                {
                    b.Property<int>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idUsers");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsers"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsFirstLogin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("IdUsers");

                    b.HasIndex(new[] { "Email" }, "Email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "Users_Roles_idx");

                    b.HasIndex(new[] { "IdUsers" }, "idUsers_UNIQUE")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OlimpBack.Models.AddDetail", b =>
                {
                    b.HasOne("OlimpBack.Models.Department", "Department")
                        .WithMany("AddDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("AddDetails_Departments");

                    b.HasOne("OlimpBack.Models.AddDiscipline", "IdAddDetailsNavigation")
                        .WithOne("AddDetail")
                        .HasForeignKey("OlimpBack.Models.AddDetail", "IdAddDetails")
                        .IsRequired()
                        .HasConstraintName("AddDeteils_AddDisciplines");

                    b.Navigation("Department");

                    b.Navigation("IdAddDetailsNavigation");
                });

            modelBuilder.Entity("OlimpBack.Models.AddDiscipline", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationalDegree", "DegreeLevel")
                        .WithMany("AddDisciplines")
                        .HasForeignKey("DegreeLevelId")
                        .HasConstraintName("AddDisciplines_EducationalDegree");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("AddDisciplines")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("AddDisciplines_ Faculties");

                    b.HasOne("OlimpBack.Models.CatalogYear", "IdCatalogNavigation")
                        .WithMany("AddDisciplines")
                        .HasForeignKey("IdCatalog")
                        .IsRequired()
                        .HasConstraintName("AddDisciplines_CatalogYears_FK");

                    b.HasOne("OlimpBack.Models.TypeOfDiscipline", "Type")
                        .WithMany("AddDisciplines")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("AddDisciplines_Type");

                    b.Navigation("DegreeLevel");

                    b.Navigation("Faculty");

                    b.Navigation("IdCatalogNavigation");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("OlimpBack.Models.AdminsPersonal", b =>
                {
                    b.HasOne("OlimpBack.Models.Department", "Department")
                        .WithMany("AdminsPersonals")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("AdminsPersonal_Department");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("AdminsPersonals")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("AdminsPersonal_Faculties");

                    b.HasOne("OlimpBack.Models.User", "User")
                        .WithMany("AdminsPersonals")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("AdminsPersonal_Users");

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OlimpBack.Models.BindAddDiscipline", b =>
                {
                    b.HasOne("OlimpBack.Models.AddDiscipline", "AddDisciplines")
                        .WithMany("BindAddDisciplines")
                        .HasForeignKey("AddDisciplinesId")
                        .IsRequired()
                        .HasConstraintName("Bind_AddDisciple");

                    b.HasOne("OlimpBack.Models.Student", "Student")
                        .WithMany("BindAddDisciplines")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("Bind_Student");

                    b.Navigation("AddDisciplines");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OlimpBack.Models.BindEvent", b =>
                {
                    b.HasOne("OlimpBack.Models.Event", "Event")
                        .WithMany("BindEvents")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("BindEvent_Event");

                    b.HasOne("OlimpBack.Models.Student", "Student")
                        .WithMany("BindEvents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("BindEvents_Student");

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OlimpBack.Models.BindExtraActivity", b =>
                {
                    b.HasOne("OlimpBack.Models.RegulationOnAddPoint", "Refulation")
                        .WithMany("BindExtraActivities")
                        .HasForeignKey("RefulationId")
                        .IsRequired()
                        .HasConstraintName("BindExtraActivity_Regulation");

                    b.HasOne("OlimpBack.Models.Student", "Student")
                        .WithMany("BindExtraActivities")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("BindExtraActivity_Student");

                    b.Navigation("Refulation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OlimpBack.Models.BindLoansMain", b =>
                {
                    b.HasOne("OlimpBack.Models.AddDiscipline", "AddDisciplines")
                        .WithMany("BindLoansMains")
                        .HasForeignKey("AddDisciplinesId")
                        .IsRequired()
                        .HasConstraintName("BindLoansMain_AddDisciplines");

                    b.HasOne("OlimpBack.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("BindLoansMains")
                        .HasForeignKey("EducationalProgramId")
                        .IsRequired()
                        .HasConstraintName("BindLoansMain_EducationalProgram");

                    b.Navigation("AddDisciplines");

                    b.Navigation("EducationalProgram");
                });

            modelBuilder.Entity("OlimpBack.Models.BindMainDiscipline", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("BindMainDisciplines")
                        .HasForeignKey("EducationalProgramId")
                        .IsRequired()
                        .HasConstraintName("BindMainDisciplines_EducationalProgram");

                    b.Navigation("EducationalProgram");
                });

            modelBuilder.Entity("OlimpBack.Models.BindRolePermission", b =>
                {
                    b.HasOne("OlimpBack.Models.Permission", "Permission")
                        .WithMany("BindRolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("BindRolePermission_Permission");

                    b.HasOne("OlimpBack.Models.Role", "Role")
                        .WithMany("BindRolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("BindRolePermission_Role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OlimpBack.Models.BindStudentsFavouriteDiscipline", b =>
                {
                    b.HasOne("OlimpBack.Models.AddDiscipline", "IdAddDisciplineNavigation")
                        .WithMany("BindStudentsFavouriteDisciplines")
                        .HasForeignKey("IdAddDiscipline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("BindStudentsFavouriteDisciplines_AddDisciplines_FK");

                    b.HasOne("OlimpBack.Models.Student", "IdStudentNavigation")
                        .WithMany("BindStudentsFavouriteDisciplines")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("BindStudentsFavouriteDisciplines_Student_FK");

                    b.Navigation("IdAddDisciplineNavigation");

                    b.Navigation("IdStudentNavigation");
                });

            modelBuilder.Entity("OlimpBack.Models.Department", b =>
                {
                    b.HasOne("OlimpBack.Models.AdminsPersonal", "Admin")
                        .WithMany("Departments")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("Department_Admin");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("Department_Faculties");

                    b.Navigation("Admin");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("OlimpBack.Models.DisciplineChoicePeriod", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationalDegree", "DegreeLevel")
                        .WithMany("DisciplineChoicePeriods")
                        .HasForeignKey("DegreeLevelId")
                        .IsRequired()
                        .HasConstraintName("fk_dcp_degreeLevel");

                    b.HasOne("OlimpBack.Models.Department", "Department")
                        .WithMany("DisciplineChoicePeriods")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_dcp_department");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("DisciplineChoicePeriods")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("fk_dcp_faculty");

                    b.Navigation("DegreeLevel");

                    b.Navigation("Department");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("OlimpBack.Models.EducationalProgram", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationalDegree", "Degree")
                        .WithMany("EducationalPrograms")
                        .HasForeignKey("DegreeId")
                        .IsRequired()
                        .HasConstraintName("EducationalProgram_EducationalDegree");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("OlimpBack.Models.Event", b =>
                {
                    b.HasOne("OlimpBack.Models.RegulationOnAddPoint", "Regulation")
                        .WithMany("Events")
                        .HasForeignKey("RegulationId")
                        .IsRequired()
                        .HasConstraintName("Event_Regultion");

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("OlimpBack.Models.Faculty", b =>
                {
                    b.HasOne("OlimpBack.Models.AdminsPersonal", "Admin")
                        .WithMany("Faculties")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("Faculties_Admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("OlimpBack.Models.Group", b =>
                {
                    b.HasOne("OlimpBack.Models.AdminsPersonal", "Admin")
                        .WithMany("Groups")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("Group_Admin");

                    b.HasOne("OlimpBack.Models.EducationalDegree", "Degree")
                        .WithMany("Groups")
                        .HasForeignKey("DegreeId")
                        .HasConstraintName("Group_Degree");

                    b.HasOne("OlimpBack.Models.Department", "Department")
                        .WithMany("Groups")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("Group_Department");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("Groups")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("Group_Faculties");

                    b.HasOne("OlimpBack.Models.EducationalProgram", "IdEducationalProgramNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("IdEducationalProgram")
                        .HasConstraintName("FK_Group_EducationalProgram");

                    b.HasOne("OlimpBack.Models.Speciality", "IdSpecialityNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("IdSpeciality")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Group_Speciality");

                    b.HasOne("OlimpBack.Models.Specialization", "IdSpecializationNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Group_Specialization");

                    b.HasOne("OlimpBack.Models.StudyForm", "IdStudyFormNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("IdStudyForm")
                        .HasConstraintName("FK_Group_StudyForm");

                    b.Navigation("Admin");

                    b.Navigation("Degree");

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("IdEducationalProgramNavigation");

                    b.Navigation("IdSpecialityNavigation");

                    b.Navigation("IdSpecializationNavigation");

                    b.Navigation("IdStudyFormNavigation");
                });

            modelBuilder.Entity("OlimpBack.Models.MainGrade", b =>
                {
                    b.HasOne("OlimpBack.Models.BindMainDiscipline", "MainDisciplines")
                        .WithMany("MainGrades")
                        .HasForeignKey("MainDisciplinesId")
                        .IsRequired()
                        .HasConstraintName("MainGrade_MainDisciplines");

                    b.HasOne("OlimpBack.Models.Student", "Student")
                        .WithMany("MainGrades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_MainGrade_Student");

                    b.Navigation("MainDisciplines");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OlimpBack.Models.Member", b =>
                {
                    b.HasOne("OlimpBack.Models.RolesInSg", "RoleInSg")
                        .WithMany("Members")
                        .HasForeignKey("RoleInSgid")
                        .IsRequired()
                        .HasConstraintName("Members_RoleInSG");

                    b.HasOne("OlimpBack.Models.Student", "Student")
                        .WithMany("Members")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("Members_Students");

                    b.HasOne("OlimpBack.Models.SubDivisionsSg", "SubDivision")
                        .WithMany("Members")
                        .HasForeignKey("SubDivisionId")
                        .IsRequired()
                        .HasConstraintName("Members_SubDivisionsSG");

                    b.Navigation("RoleInSg");

                    b.Navigation("Student");

                    b.Navigation("SubDivision");
                });

            modelBuilder.Entity("OlimpBack.Models.Normative", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationalDegree", "DegreeLevel")
                        .WithMany("Normatives")
                        .HasForeignKey("DegreeLevelId")
                        .HasConstraintName("Normative_Degree");

                    b.Navigation("DegreeLevel");
                });

            modelBuilder.Entity("OlimpBack.Models.Notification", b =>
                {
                    b.HasOne("OlimpBack.Models.NotificationTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("Notification_NotificationTemplate");

                    b.HasOne("OlimpBack.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Notification_Users");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OlimpBack.Models.Role", b =>
                {
                    b.HasOne("OlimpBack.Models.Role", "ParentRole")
                        .WithMany("InverseParentRole")
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Role_ParentRole");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("OlimpBack.Models.Speciality", b =>
                {
                    b.HasOne("OlimpBack.Models.Branch", "IdBranchNavigation")
                        .WithMany("Specialities")
                        .HasForeignKey("IdBranch")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Speciality_Branch");

                    b.HasOne("OlimpBack.Models.Department", "IdDepartmentNavigation")
                        .WithMany("Specialities")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Speciality_Department");

                    b.HasOne("OlimpBack.Models.Faculty", "IdFacultyNavigation")
                        .WithMany("Specialities")
                        .HasForeignKey("IdFaculty")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Speciality_Faculty");

                    b.Navigation("IdBranchNavigation");

                    b.Navigation("IdDepartmentNavigation");

                    b.Navigation("IdFacultyNavigation");
                });

            modelBuilder.Entity("OlimpBack.Models.Specialization", b =>
                {
                    b.HasOne("OlimpBack.Models.Speciality", "IdSpecialityNavigation")
                        .WithMany("Specializations")
                        .HasForeignKey("IdSpeciality")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Specialization_Speciality");

                    b.Navigation("IdSpecialityNavigation");
                });

            modelBuilder.Entity("OlimpBack.Models.Student", b =>
                {
                    b.HasOne("OlimpBack.Models.EducationStatus", "EducationStatus")
                        .WithMany("Students")
                        .HasForeignKey("EducationStatusId")
                        .IsRequired()
                        .HasConstraintName("Students_EducationStatus");

                    b.HasOne("OlimpBack.Models.EducationalDegree", "EducationalDegree")
                        .WithMany("Students")
                        .HasForeignKey("EducationalDegreeId")
                        .IsRequired()
                        .HasConstraintName("Students_EducationalDegree");

                    b.HasOne("OlimpBack.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Students")
                        .HasForeignKey("EducationalProgramId")
                        .IsRequired()
                        .HasConstraintName("Students_EducationalProgram");

                    b.HasOne("OlimpBack.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("Students_Faculties");

                    b.HasOne("OlimpBack.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("Students_Group");

                    b.HasOne("OlimpBack.Models.StudyForm", "StudyForm")
                        .WithMany("Students")
                        .HasForeignKey("StudyFormId")
                        .IsRequired()
                        .HasConstraintName("Students_StudyForm");

                    b.HasOne("OlimpBack.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Students_Users");

                    b.Navigation("EducationStatus");

                    b.Navigation("EducationalDegree");

                    b.Navigation("EducationalProgram");

                    b.Navigation("Faculty");

                    b.Navigation("Group");

                    b.Navigation("StudyForm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OlimpBack.Models.User", b =>
                {
                    b.HasOne("OlimpBack.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OlimpBack.Models.AddDiscipline", b =>
                {
                    b.Navigation("AddDetail");

                    b.Navigation("BindAddDisciplines");

                    b.Navigation("BindLoansMains");

                    b.Navigation("BindStudentsFavouriteDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.AdminsPersonal", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Faculties");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("OlimpBack.Models.BindMainDiscipline", b =>
                {
                    b.Navigation("MainGrades");
                });

            modelBuilder.Entity("OlimpBack.Models.Branch", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("OlimpBack.Models.CatalogYear", b =>
                {
                    b.Navigation("AddDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.Department", b =>
                {
                    b.Navigation("AddDetails");

                    b.Navigation("AdminsPersonals");

                    b.Navigation("DisciplineChoicePeriods");

                    b.Navigation("Groups");

                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("OlimpBack.Models.EducationStatus", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.EducationalDegree", b =>
                {
                    b.Navigation("AddDisciplines");

                    b.Navigation("DisciplineChoicePeriods");

                    b.Navigation("EducationalPrograms");

                    b.Navigation("Groups");

                    b.Navigation("Normatives");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.EducationalProgram", b =>
                {
                    b.Navigation("BindLoansMains");

                    b.Navigation("BindMainDisciplines");

                    b.Navigation("Groups");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.Event", b =>
                {
                    b.Navigation("BindEvents");
                });

            modelBuilder.Entity("OlimpBack.Models.Faculty", b =>
                {
                    b.Navigation("AddDisciplines");

                    b.Navigation("AdminsPersonals");

                    b.Navigation("Departments");

                    b.Navigation("DisciplineChoicePeriods");

                    b.Navigation("Groups");

                    b.Navigation("Specialities");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("OlimpBack.Models.Permission", b =>
                {
                    b.Navigation("BindRolePermissions");
                });

            modelBuilder.Entity("OlimpBack.Models.RegulationOnAddPoint", b =>
                {
                    b.Navigation("BindExtraActivities");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("OlimpBack.Models.Role", b =>
                {
                    b.Navigation("BindRolePermissions");

                    b.Navigation("InverseParentRole");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OlimpBack.Models.RolesInSg", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OlimpBack.Models.Speciality", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("OlimpBack.Models.Specialization", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("OlimpBack.Models.Student", b =>
                {
                    b.Navigation("BindAddDisciplines");

                    b.Navigation("BindEvents");

                    b.Navigation("BindExtraActivities");

                    b.Navigation("BindStudentsFavouriteDisciplines");

                    b.Navigation("MainGrades");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("OlimpBack.Models.StudyForm", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("OlimpBack.Models.SubDivisionsSg", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OlimpBack.Models.TypeOfDiscipline", b =>
                {
                    b.Navigation("AddDisciplines");
                });

            modelBuilder.Entity("OlimpBack.Models.User", b =>
                {
                    b.Navigation("AdminsPersonals");

                    b.Navigation("Notifications");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
